apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "awx-operator.fullname" . }}-proxy-rolebinding
  labels: {{ include "awx-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "awx-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
