apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awx-operator.fullname" . }}-awx-manager-config
  labels: {{ include "awx-operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    ---
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :6789
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 811c9dc5.ansible.com
