apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-operator-awx-manager-rolebinding
  labels: {{ include "awx-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator-awx-manager-role
subjects:
- kind: ServiceAccount
  name: awx-operator-controller-manager
  namespace: {{ .Release.Namespace }}
