apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "awx-operator.fullname" . }}-leader-election-rolebinding
  labels: {{ include "awx-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "awx-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
