apiVersion: v1
kind: Service
metadata:
  name: awx-operator-controller-manager-metrics-service
  labels: {{ include "awx-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector: {{ include "awx-operator.selectorLabels" . | nindent 4 }}
